export const LookupTable = [
  {
    pillar_id: "energy_pillar",
    question: [
      {
        formulaId: "Formula_1",
        formula: "inputField003 * referenceValue",
        questionId: "qstn_id_1",
        lookup: [
          {
            inputField001: "Solar Energy",
            inputField002: "Supply Chain",
            inputField004: "16-20",
            referenceValue: "0.1",
          },
          {
            inputField001: "Solar Energy",
            inputField002: "Supply chain",
            inputField004: "21-25",
            referenceValue: "0.2",
          },
          {
            inputField001: "Solar Energy",
            inputField002: "Manufacturing unit",
            inputField004: "16-20",
            referenceValue: "0.3",
          },
          {
            inputField001: "Solar Energy",
            inputField002: "Manufacturing unit",
            inputField004: "21-25",
            referenceValue: "0.4",
          },
          {
            inputField001: "Wind Energy",
            inputField002: "Supply Chain",
            inputField004: "16-20",
            referenceValue: "0.5",
          },
          {
            inputField001: "Wind Energy",
            inputField002: "Supply chain",
            inputField004: "21-25",
            referenceValue: "0.6",
          },
          {
            inputField001: "Wind Energy",
            inputField002: "Manufacturing unit",
            inputField004: "16-20",
            referenceValue: "0.7",
          },
          {
            inputField001: "Wind Energy",
            inputField002: "Manufacturing unit",
            inputField004: "21-25",
            referenceValue: "0.8",
          },
          {
            inputField001: "Hydropower",
            inputField002: "Supply Chain",
            inputField004: "16-20",
            referenceValue: "0.9",
          },
          {
            inputField001: "Hydropower",
            inputField002: "Supply chain",
            inputField004: "21-25",
            referenceValue: "0.10",
          },
          {
            inputField001: "Hydropower",
            inputField002: "Manufacturing unit",
            inputField004: "16-20",
            referenceValue: "0.11",
          },
          {
            inputField001: "Hydropower",
            inputField002: "Manufacturing unit",
            inputField004: "21-25",
            referenceValue: "0.12",
          },
        ],
      },
      {
        formulaId: "Formula_2",
        formula: "inputField001 * referenceValue",
        questionId: "qstn_id_2",
        lookup: [
          {
            referenceValue: "0.13",
          },
        ],
      },
      {
        formulaId: "Formula_3",
        formula: "inputField002 * referenceValue",
        questionId: "qstn_id_3",
        lookup: [
          {
            inputField001:"Office",
            referenceValue: "0.14",
          },
          {
            inputField001:"Factory",
            referenceValue: "0.15",
          },
          {
            inputField001:"Warehouse",
            referenceValue: "0.16",
          },
        ],
      },
    ],
  },
  {
    pillar_id: "packaging_pillar",
    question: [
      {
        formulaId: "Formula_01",
        formula: "inputField001 * inputField003 * referenceValue",
        questionId: "qstn_id_1",
        lookup: [{
          inputField002:"PET",
          referenceValue: "0.17",
        },
        {
          inputField002:"Glass",
          referenceValue: "0.18",
        },
        {
          inputField002:"Paper",
          referenceValue: "0.19",
        }],
      },
      {
        formulaId: "Formula_02",
        formula: "(inputField004 - inputField005) * referenceValue",
        questionId:"qstn_id_4",
        lookup:[
          
          {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"0.20",
        },
        {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"0.21",
        },
        {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"0.22",
        },
        {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"23",
        },
        {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"24",
        },
        {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"25",
        },
        {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"26",
        },
        {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"27",
        },
        {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"28",
        },
        {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"29",
        },
        {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"30",
        },
        {
          inputField001:"Food",
          inputField002:"Box",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"31",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"32",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"33",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"34",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"35",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"36",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"37",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"38",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"39",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"40",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"41",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"42",
        },
        {
          inputField001:"Food",
          inputField002:"Bottle",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"43",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"44",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"45",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"46",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"47",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"48",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"49",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"50",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"51",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"52",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"53",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"54",
        },
        {
          inputField001:"Food",
          inputField002:"Tray",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"55",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"56",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"57",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"58",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"59",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"60",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"61",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"62",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"63",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"64",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"65",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"66",
        },
        {
          inputField001:"Food",
          inputField002:"HangTags",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"67",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"68",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"69",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"70",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"71",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"72",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"73",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"74",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"75",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"76",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"77",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"78",
        },
        {
          inputField001:"Electronics",
          inputField002:"Box",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"79",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"80",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"81",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"82",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"83",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"84",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"85",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"86",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"87",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"88",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"89",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"90",
        },
        {
          inputField001:"Electronics",
          inputField002:"Bottle",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"91",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"92",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"93",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"94",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"95",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"96",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"97",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"98",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"99",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"100",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"101",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"102",
        },
        {
          inputField001:"Electronics",
          inputField002:"Tray",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"103",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"104",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"105",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"106",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"107",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"108",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"109",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"110",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"111",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"112",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"113",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"114",
        },
        {
          inputField001:"Electronics",
          inputField002:"HangTags",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"115",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"116",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"117",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"118",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"119",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"120",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"121",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"122",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"123",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"124",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"125",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"126",
        },
        {
          inputField001:"Apparels",
          inputField002:"Box",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"127",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"128",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"129",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"130",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"131",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"132",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"133",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"134",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"135",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"136",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"137",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"138",
        },
        {
          inputField001:"Apparels",
          inputField002:"Bottle",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"139",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"140",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"141",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"142",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"143",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"144",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"145",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"146",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"147",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"148",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"149",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"150",
        },
        {
          inputField001:"Apparels",
          inputField002:"Tray",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"151",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"Paper",
          inputField008:"Good",
          referenceValue:"152",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"Paper",
          inputField008:"Better",
          referenceValue:"153",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"Paper",
          inputField008:"Not Recommended",
          referenceValue:"154",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"Glass",
          inputField008:"Good",
          referenceValue:"155",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"Glass",
          inputField008:"Better",
          referenceValue:"156",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"Glass",
          inputField008:"Not Recommended",
          referenceValue:"157",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"Alumininum",
          inputField008:"Good",
          referenceValue:"158",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"Alumininum",
          inputField008:"Better",
          referenceValue:"159",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"Alumininum",
          inputField008:"Not Recommended",
          referenceValue:"160",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"PVC",
          inputField008:"Good",
          referenceValue:"161",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"PVC",
          inputField008:"Better",
          referenceValue:"162",
        },
        {
          inputField001:"Apparels",
          inputField002:"HangTags",
          inputField003:"PVC",
          inputField008:"Not Recommended",
          referenceValue:"163",
        },

      ]
      }
    ],
  },
  {
    pillar_id: "waste_pillar",
    question: [
      {
        formulaId: "Formula_1",
        formula: "inputField002 * inputFiled003 * inputFiled004 * inputFiled005 * referenceValue",
        questionId: "qstn_id_1",
        lookup:[ {
          inputField001: "Electronic",
          referenceValue: "1",
        },
        {
          inputField001: "Aluminium Cans",
          referenceValue: "1.1",
        },
        {
          inputField001: "Glass",
          referenceValue: "1.2",
        }],
      },
    ],
  },
];
